### ISSUE TITLE
Generating Customer - Random Contact - Uses Account rather than Contact

### ISSUE THREAD

**Issue by sabrish** [LinkeD365/MockarooDataMunger#18]
While generating data for Customer field and Mock Type as Random Contact, it generates data using Account, rather than Contact.

![image](https://user-images.githubusercontent.com/2657337/98507424-7971d580-2255-11eb-85cd-41d32b79b99b.png)

**Comment by LinkeD365** [comment]
@sabrish thanks for raising, was an easy fix this morning, please let me know
